CREATE TABLE IF NOT EXISTS leaderboard (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  wpm INT NOT NULL,
  accuracy FLOAT NOT NULL,
  time_taken FLOAT NOT NULL,
  played_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
